config/routes.rb
Rails.application.routes.draw do

  root 'topics#index'

  resources :topics, :cards, :schichida_sessions, :doman_sessions, :math_sessions
  resources :user_sessions, :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    can :update, User, { id: user.try(:id) }
    can :create, User

    if user

      if user.admin?
        can :manage, :cards
      end
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord

  belongs_to :content
  belongs_to :image
  belongs_to :language
  belongs_to :topic
  has_and_belongs_to_many :schichida_sessions

  accepts_nested_attributes_for :content, reject_if: proc { |attrs| attrs[:audio].blank? }
  accepts_nested_attributes_for :image, reject_if: proc { |attrs| attrs[:image].blank? }

  validates :content, :image, :language, :topic, presence: true
  validates :content, uniqueness: { scope: :image }

  def topic_name
    topic.try(:name)
  end

  def topic_name=(name)
    self.topic = Topic.find_or_create_by(name: name, language: language) if name.present?
  end

end

app/models/content.rb
class Content < ApplicationRecord
  ALLOWED_AUDIO = [
    'audio/mpeg',
    'audio/x-mpeg',
    'audio/mp3',
    'audio/x-mp3',
    'audio/mpeg3',
    'audio/x-mpeg3',
    'audio/mpg',
    'audio/x-mpg',
    'audio/x-mpegaudio',
    'application/octet-stream'
  ]

  has_attached_file :audio,
                    storage: :cloudinary,
                    cloudinary_resource_type: :video,
                    path: ":class/:attachment/:id_partition/:style/:filename"

  validates_attachment_content_type :audio, content_type: ALLOWED_AUDIO
  validates :audio, presence: true
  validates :text, presence: true, uniqueness: true

end

app/models/image.rb
class Image < ApplicationRecord

  has_attached_file :image,
                    storage: :cloudinary,
                    path: ":class/:attachment/:id_partition/:style/:filename"

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :image, presence: true

end

app/models/language.rb
class Language < ApplicationRecord  
end

app/models/schichida_session.rb
class SchichidaSession < ApplicationRecord

  CARDS_COUNT = 20

  belongs_to :user
  has_and_belongs_to_many :cards

  def build_cards
    self.cards = new_cards.order(:topic_id).limit(CARDS_COUNT)
  end

  def prev_session
    SchichidaSession.where(user: user).order('created_at DESC').first
  end

  private

  def new_cards
    new_cards = Card
      .left_outer_joins(:schichida_sessions)
      .where(schichida_sessions: {id: nil})

    if prev_session
      new_cards.order(opened_topic_first)
    else
      new_cards
    end
  end

  def opened_topic_first
    Card.send(:sanitize_sql_array, ['case when topic_id = %d then 0 else 1 end', opened_topic_id])
  end

  def opened_topic_id
    prev_session.cards.pluck(:topic_id).first
  end
end

app/models/topic.rb
class Topic < ApplicationRecord

  belongs_to :language
  has_many :cards

  def self.search(term)
    where('LOWER(name) LIKE :term', term: "%#{term.downcase}%")
  end

end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes["password"] }
  validates :password, confirmation: true, if: -> { new_record? || changes["password"] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes["password"] }

  validates :email, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include CanCan::ControllerAdditions

  protect_from_forgery with: :exception
end

app/controllers/card_sessions_controller.rb
class CardSessionsController < ApplicationController
  def new
    @card_session = CardSession.new
  end

  def create
    @card_session = CardSession.new
    @card_session.build_cards
    if @card_session.save
      redirect_to @card_session
    else
      render :new
    end
  end

  def show
    card_session = CardSession.find params[:id]

    @cards = card_session.cards.to_a
    @first_card = @cards.shift
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def new
    @card = Card.new
    @card.language = Language.find(params[:language_id]) if params[:language_id]
    @card.topic_name = params[:topic_name] if params[:topic_name]

    @card.build_image
    @card.build_content
  end

  def create
    @card = Card.new(card_params)

    if @card.save
      redirect_to @card.topic
    else
      render :new
    end
  end

  def edit
    @card = Card.find(params[:id])
  end

  def update
    @card = Card.find(params[:id])

    if @card.update(card_params)
      redirect_to @card.topic
    else
      render :edit
    end
  end

  def show
    @card = Card.find(params[:id])
  end

  private

  def card_params
    params
      .require(:card)
      .permit(
        :content_id,
        :image_id,
        :language_id,
        :topic_name,
        content_attributes: [:text, :audio],
        image_attributes: [:image]
      )
  end

end

app/controllers/schichida_sessions_controller.rb
class SchichidaSessionsController < ApplicationController
  def new
    @schichida_session = SchichidaSession.new
  end

  def create
    @schichida_session = SchichidaSession.new(user: current_user)
    if params[:topic_id]
      topic = Topic.find(params[:topic_id])
      @schichida_session.cards = topic.try(:cards)
    else
      @schichida_session.build_cards
    end

    if @schichida_session.cards.empty?
      redirect_to topics_url
    elsif @schichida_session.save
      redirect_to @schichida_session
    else
      render :new
    end
  end

  def show
    schichida_session = SchichidaSession.find params[:id]

    @cards = schichida_session.cards.to_a
    @first_card = @cards.shift
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.where(language_id: current_user.cards_language_id) if current_user
    @topics ||= Topic.where(language_id: params[:language_id])
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)

    if @topic.save
      params[:topic][:images].each do |image|
        CardCreator.new(@topic, image).perform
      end

      redirect_to @topic
    else
      render :new
    end
  end

  def topic_params
    params.require(:topic).permit(:name, :language_id)
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to root_url
    else
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_back_or_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: %i(edit update destroy)
  before_action :require_login, only: %i(edit update)

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to edit_user_url(@user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_url
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :email,
      :password,
      :password_confirmation,
      :site_language_id,
      :cards_language_id,
      :schichida,
      :doman,
      :math
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/cards/_form.html.slim
= form_for @card do |f|
  .form-group.row
    .col-form-label.col-sm-2= f.label :language
    .col-sm-4
      = f.collection_select :language_id, Language.order(:name), :id, :name, {}, {class: 'custom-select'}

  .form-group.row
    .col-form-label.col-sm-2= f.label :topic_name
    .col-sm-4
      = f.text_field :topic_name,
        id: 'card_topic_name',
        class: 'form-control',
        data: {autocomplete_source: Topic.pluck(:name).to_json}
      = @card.errors.full_messages_for(:topic).first

  = f.fields_for :content do |c|
    .form-group.row
      .col-form-label.col-sm-2= c.label :text
      .col-sm-4
        = c.text_field :text, class: 'form-control text'
        = @card.errors.full_messages_for(:'content.text').first

    .form-group.row
      .col-form-label.col-sm-2= c.label :audio, 'Audio file'
      .col-sm-4
        = c.file_field :audio
        = @card.content.try(:audio_file_name)
        = @card.errors.full_messages_for(:'content.audio').first

  = f.fields_for :image do |i|
    .form-group.row
      .col-form-label.col-sm-2= i.label :image, 'Image file'
      .col-sm-4
        = i.file_field :image
        = @card.image.try(:image_file_name)
        = @card.errors.full_messages_for(:'image.image').first

  .form-group.row
    .col-sm-10.offset-sm-2= f.submit 'Save', class: 'btn btn-primary'

app/views/cards/show.html.slim
.card
  = image_tag @card.image.image, class: 'image'
  = audio_tag @card.content.audio, class: 'audio', autoplay: true

app/views/layouts/_menu.html.slim
nav.navbar.navbar-inverse.bg-inverse.navbar-toggleable-md.justify-content-end
  .container
    .navbar-nav
      = link_to 'Dashboard', dashboard_url, class: 'nav-item nav-link'    
      = link_to 'Index', topics_url, class: 'nav-item nav-link'
      - if logged_in?
        = link_to 'Settings', edit_user_url(current_user), class: 'nav-item nav-link'
        = link_to 'Logout', logout_url, class: 'nav-item nav-link'
      - else
        = link_to 'Login', login_url, class: 'nav-item nav-link'

app/views/layouts/application.slim
doctype html
html
  head
    title Imagenarium
    meta name='viewport' content='width=device-width, initial-scale=1.0'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags

  body
    .container
      .mt-4= yield

app/views/schichida_sessions/show.html.slim
.row
  .col.text-center
    .carousel.slide{data-ride='carousel' data-interval=2000}
      .carousel-inner{role='listbox'}
        .carousel-item.active
          .card
            = image_tag @first_card.image.image
            = audio_tag @first_card.content.audio, autoplay: true

        - @cards.each do |card|
          .carousel-item
            .card
              = image_tag card.image.image
              = audio_tag card.content.audio

app/views/topics/index.html.slim
= form_tag :topics, method: :get do
  - unless current_user.try(:cards_language_id)
    .form-group
      = select_tag :language_id,
        options_from_collection_for_select(Language.order(:name), :id, :name, params[:language_id]),
        class: 'custom-select',
        prompt: t(:select_language),
        onchange: 'this.form.submit();'

- @topics.each do |topic|
  = link_to topic_path(topic), class: 'btn btn-secondary m-1' do
    = topic.name
    |&emsp;
    span.badge.badge-pill.badge-default= topic.cards.count

app/views/topics/new.html.slim
= form_for @topic, html: {multipart: true} do |f|
  .form-group.row
    .col-form-label.col-sm-2= f.label :language
    .col-sm-4
      = f.collection_select :language_id, Language.order(:name), :id, :name, {}, {class: 'custom-select'}

  .form-group.row
    .col-form-label.col-sm-2= f.label :name
    .col-sm-4
      = f.text_field :name, class: 'form-control'
      = @topic.errors.full_messages_for(:name).first

  .form-group.row
    .col-form-label.col-sm-2= f.label :images, 'Image files'
    .col-sm-4
      = f.file_field :images, multiple: true, class: 'form-control'

  .form-group.row
    .col-sm-10.offset-sm-2= f.submit 'Save', class: 'btn btn-primary'

app/views/topics/show.html.slim
h3= @topic.name
ul.nav.justify-content-end
  li.nav-item= link_to 'New card', new_card_path(language_id: @topic.language_id, topic_name: @topic.name)
  li.nav-item= link_to 'New session', schichida_sessions_path(topic_id: @topic.id), method: :post

.card-columns
  - @topic.cards.each do |card|
    .card
      = image_tag card.image.image, class: 'card-img-top img-fluid'
      = audio_tag card.content.audio, controls: 'controls'

      .card-block
        h4.card-title= card.content.text

      .card-block
        = link_to 'Edit', edit_card_path(card), class: 'card-link'
        = link_to 'Delete',
                  card_path(card),
                  method: :delete,
                  data: {:confirm => 'Are you sure?'},
                  class: 'card-link'

app/views/user_sessions/new.html.slim
= form_tag user_sessions_path, method: :post do
  .form-group
    = label_tag :email
    = text_field_tag :email, nil, class: 'form-control'

  .form-group
    = label_tag :password
    = password_field_tag :password, nil, class: 'form-control'

  .form-group
    = submit_tag :login, class: 'btn btn-primary'
    |&nbsp;
    |or
    |&nbsp;
    = link_to :registration, new_user_path

app/views/users/edit.html.slim
ul.nav.nav-tabs{role='tablist'}
  li.nav-item
    = link_to 'Account', '#account', class: 'nav-link active', role: 'tab', 'data-toggle': 'tab'
  li.nav-item
    = link_to 'Notifications', '#notifications', class: 'nav-link', role: 'tab', 'data-toggle': 'tab'
  li.nav-item
    = link_to 'Dashboard', '#dashboard', class: 'nav-link', role: 'tab', 'data-toggle': 'tab'
  li.nav-item
    = link_to 'Statistics', '#', class: 'nav-link', role: 'tab', 'data-toggle': 'tab'

.tab-content
  #account.tab-pane.active{role='tabpanel'}
    = form_for @user, role: 'form', autocomplete: 'off' do |f|
      h4.mt-4 Change password
      hr
      .form-group
        = f.label :password
        = f.password_field :password, autocomplete: 'off', class: 'form-control'

      .form-group
        = f.label :password_confirmation
        = f.password_field :password_confirmation, class: 'form-control'

      .form-group
        = f.submit 'Update password', class: 'btn'        
            
  #notifications.tab-pane
    h4.mt-4 Notifications
    hr
    p Choose notifications you receive.
    
  #dashboard.tab-pane
    = form_for @user, role: 'form', autocomplete: 'off' do |f|
    
      h4.mt-4 Languages
      hr
      .form-group
        = f.label 'Site language'
        = f.select :site_language_id,
          options_from_collection_for_select(Language.order(:name), :id, :name, params[:language_id]),
          class: 'custom-select form-control'
          
      .form-group
        = f.label 'Cards language'
        = f.select :cards_language_id,
          options_from_collection_for_select(Language.order(:name), :id, :name, params[:language_id]),
          class: 'custom-select form-control'
          
      h4.mt-4 Cards sets
      hr      
      .form-group
        = label_tag nil,  class: 'custom-control custom-checkbox' do
          = f.check_box :schichida, class: 'custom-control-input'
          span.custom-control-indicator
          span.custom-control-description Schichida cards
          
      .form-group
        = label_tag nil,  class: 'custom-control custom-checkbox' do
          = f.check_box :math, class: 'custom-control-input'
          span.custom-control-indicator          
          span.custom-control-description Math cards
        
      .form-group
        = label_tag nil,  class: 'custom-control custom-checkbox' do
          = f.check_box :doman, class: 'custom-control-input'
          span.custom-control-indicator          
          span.custom-control-description Doman cards
          
      .form-group
        = f.submit 'Update', class: 'btn'      

  #statistics.tab-pane
    

      

app/views/users/new.html.slim
= form_for @user, role: 'form', autocomplete: 'off' do |f|
  .form-group
    = f.label :email
    = f.text_field :email, autocomplete: 'off', class: 'form-control'

  .form-group
    = f.label :password
    = f.password_field :password, autocomplete: 'off', class: 'form-control'

  .form-group
    = f.label :password_confirmation
    = f.password_field :password_confirmation, class: 'form-control'

  .form-group
    = f.submit :save, class: 'btn btn-primary'